"""
Locust load tests for the JSONPlaceholder /posts endpoint.

Run an interactive load test:
    locust -f performance/locustfile.py --host https://jsonplaceholder.typicode.com

Then open http://localhost:8089 in a browser, set users + spawn-rate, and start.

Run a headless smoke load test (used in CI):
    locust -f performance/locustfile.py \
        --host https://jsonplaceholder.typicode.com \
        --users 5 --spawn-rate 1 --run-time 20s --headless
"""
from locust import HttpUser, task, between


class PostsUser(HttpUser):
    """Simulates a user browsing and creating posts."""

    # Time each virtual user waits between tasks (seconds)
    wait_time = between(1, 3)

    @task(5)
    def get_single_post(self):
        """Fetch a single post — the most common operation (weight 5)."""
        self.client.get("/posts/1", name="GET /posts/{id}")

    @task(3)
    def list_posts(self):
        """List all posts (weight 3)."""
        self.client.get("/posts", name="GET /posts")

    @task(1)
    def create_post(self):
        """Create a new post — least frequent (weight 1)."""
        payload = {
            "title": "Locust load-test post",
            "body": "Generated by performance suite",
            "userId": 1,
        }
        self.client.post("/posts", json=payload, name="POST /posts")
